Fix: Remove enum keyword against blas types
This commit gets rid of the the following error encountered upon switching to 16.04 from 14.04

Error: elaborated type refers to a typedef